version: "3.8"

services:
  trainer:
    build: ./train
    container_name: trainer
    volumes:
      - ./model_store:/app/model_store
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns

  serve:
    build: 
      context: ./serve
      args:
        RUN_ID:
    container_name: torchserve
    ports:
      - "8080:8080"
    volumes:
      - ./model_store:/home/model-server/model-store

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - serve
